### ISSUE TITLE
🔎 Tabular data functions into unpackai

### ISSUE THREAD

**Issue by raynardj** [unpackAI/unpackai#14]
# 🔎 Tabular data functions into unpackai
> Pack some bulk functions from tabular week colab notebook into unpack

**Comment by faizer1989** [comment]
Could we add a few basic EDA methods for dataset exploration:

1. correlation matrix
2. histograms

In order to see:

1. the relationship between features
2. explore if the dataset is balanced/imbalanced for classification problems

**Comment by raynardj** [comment]
* [ ] delete missing value column

**Comment by raynardj** [comment]
> @raynardj Could we add a few basic EDA methods for dataset exploration:
> 
> * [ ]  correlation matrix
> * [ ]  histograms
> 
> In order to see:
> 
> 1. the relationship between features
> 2. explore if the dataset is balanced/imbalanced for classification problems

I can't see the correlation thing in the notebook except the dandogram, is that it?

**Comment by faizer1989** [comment]
> > @raynardj Could we add a few basic EDA methods for dataset exploration:
> > 
> > * [ ]   correlation matrix
> > * [ ]   histograms
> > 
> > In order to see:
> > 
> > 1. the relationship between features
> > 2. explore if the dataset is balanced/imbalanced for classification problems
> 
> I can't see the correlation thing in the notebook except the dandogram, is that it?

It's not in the notebook yet. In the previous DL 101 one students built the correlation matrix to get better insights about data. It helped him to understand dendrogram better to remove redundant features. So when we had a discussion with mentors and John, the conclusion was to add it for better data interpretabilityty

**Comment by raynardj** [comment]
> > > @raynardj Could we add a few basic EDA methods for dataset exploration:
> > > 
> > > * [ ]    correlation matrix
> > > * [ ]    histograms
> > > 
> > > In order to see:
> > > 
> > > 1. the relationship between features
> > > 2. explore if the dataset is balanced/imbalanced for classification problems
> > 
> > 
> > I can't see the correlation thing in the notebook except the dandogram, is that it?
> 
> It's not in the notebook yet. In the previous DL 101 one students built the correlation matrix to get better insights about data. It helped him to understand dendrogram better to remove redundant features. So when we had a discussion with mentors and John, the conclusion was to add it for better data interpretabilityty

Ohh I've seen it, it's like a table by nb_cols x nb_cols, the heatmap table shows the correlation intensity, right?
