### ISSUE TITLE
Create utils functions to download and unzip

### ISSUE THREAD

**Issue by jfthuong** [unpackAI/unpackai#35]
Unzip and download is a bit clumsy in fastai implementation. It would better to use our own implementation that would have unified names & arguments.

We could have following functions:

* [x] `download_unzip`
* [x] `download`
* [x] `unzip`
* [x] `url_to_text`: convert the text of a url (either the direct content if it's a text file, or the extracted text from an html if it's a page => the code is already present in `Textual` class so we could refactor it maybe.

**Comment by raynardj** [comment]
interesting mindset, you think of test before you move on the actual function. https://github.com/unpackAI/unpackai/commit/954ce59b62162d09eeb063ebe2d6cc34221fb5a4

**Comment by raynardj** [comment]
# Need to discuss
> Where do you want to keep the download function, in ```utils.py```? If that's the case u first I follow.

**Comment by raynardj** [comment]
## About ```url_to_text```
A good idea, as url could lead to text, html, csv, table in html, zip, tar.gz etc, 
* url.to_image_dataloaders()
* url.to_textual()
* url.to_df()

**Comment by jfthuong** [comment]
> # Need to discuss
> * [ ]  Where do you want to keep the download function, in `utils.py`? If that's the case u first I follow.
> * [ ]   Do we use [fastdownload](https://www.fast.ai/2021/08/02/fastdownload/) inside the function
>   
>   * [ ]  Yes
>   * [ ]  No

This is a good question.

FastDownload allows to have a progressbar updated apparently by downloading bits by bits.

However, it is a bit heavy to configure (a simple `requests.get` is super straight forward and enough for relatively simple files).

Maybe we could read size beforehand and for big file we use `fastdownload` and for small file a simple `requests` implementation?

But that would lead to heavy code with 2 implementations. weird

**Comment by jfthuong** [comment]
... and yes, I was thinking of putting in `utils`

**Comment by raynardj** [comment]
> But that would lead to heavy code with 2 implementations. weird

1 implementation is enough, for now unpackai is solely built for colab, which is insanely fast with internet, like 20g of data in 3 minutes.

I think request.get should suffice, but curl or wget can print out progress bar.

**Comment by jfthuong** [comment]
> ## About `url_to_text`
> A good idea, as url could lead to text, html, csv, table in html, zip, tar.gz etc,
> 
> * url.to_image_dataloaders()
> * url.to_textual()
> * url.to_df()

`url.to_df` is not needed since you can create a df directly from an URL (`pd.read_csv(url)`).

for `to_image_dataloaders()` I'm not sure to know what you mean. Please detail.
