### ISSUE TITLE
🍸 start app

### ISSUE THREAD

**Issue by raynardj** [unpackAI/unpackai#43]
# 🍸 Simple Start Application (interactive+ API)
**Is your feature request related to a problem? Please describe.**
Running app/ widgets/ API on model for inference

**Describe the solution you'd like**
Without any extra code or importing, when you load or trained a valid learner:
```python
learn.start_app(port=7676)
```

**Additional context**
It's less workload than we think

**Comment by jfthuong** [comment]
what do you plan to use for the App?

Shall it run from Colab? Any Jupyter? Python script? Locally or only online?

**Comment by jfthuong** [comment]
Started to implement with PR #66

**Comment by raynardj** [comment]
Well now we have ```deploy``` with ngrok. #68
