### ISSUE TITLE
🧪Create dedicated tests for functions

### ISSUE THREAD

**Issue by jfthuong** [unpackAI/unpackai#6]
We should have proper testing and coverage measures for functionalities implemented in `unpackai` package.

**Comment by raynardj** [comment]
Nice title with emoji

**Comment by raynardj** [comment]
# 🚨 Possible Pickles to Solve
> This might not be a complete list, for now I can't think of a way to arrange test to following with only python
* Many parts in this library involves frontend interactive features
* Some of the feature will start a tensorboard service on colab instance, and only accessible by colab notebook, not even anaconda jupyter. The mechanism is rather complicated and a very particular rabbit hole
