### ISSUE TITLE
The text file is too big when use Textual.from_path()

### ISSUE THREAD

**Issue by faizer1989** [unpackAI/unpackai#61]
<img width="400" alt="aaeae87087b17cd1d770395529ee129" src="https://user-images.githubusercontent.com/29976206/140610860-7122fd4e-596c-44de-a304-667394ded774.png">
<img width="646" alt="a75d57043df50d131170d5af0ca81c3" src="https://user-images.githubusercontent.com/29976206/140610878-194cd8d3-4dbd-4c02-a6e1-4e841589d29e.png">

I used read pdf function on 2.3 MB "thousand n one nights" http://islamicblessings.com/upload/A-Thousand-And-One-Nights-1.pdf

**Comment by jfthuong** [comment]
Actually, since `Conver_PDF` returns the text from PDF, you just need to do:

```python
textual = Textual(convert_PDF("/content/..../xxx.pdf"))
```
