### ISSUE TITLE
Create some code to convert .tiff to jpg

### ISSUE THREAD

**Issue by jfthuong** [unpackAI/unpackai#63]
**Is your feature request related to a problem? Please describe.**
This dataset is using .tiff: https://sites.uef.fi/spectral/odsi-db/
Each file is big and apparently embeds spectral image (one image per frequency range) + a RGB image encoded in 24-bit (usually a JPG is 8-bit).

**Describe the solution you'd like**
A function to convert

**Describe alternatives you've considered**
Following modules / posts are a good start:

* https://github.com/lfsantosgeo/ConvertTiff2Jpg/blob/master/convertTiff2Jpg.py
* https://stackoverflow.com/questions/57809780/how-to-convert-tif-image-to-jpg-using-skimage

**Additional context**
DL201

**Comment by jfthuong** [comment]
https://cs.uef.fi/pub/color/spectra/ODSI-DB/

> The database is available for download here. The oral and dental spectral image files are multipage TIFF images. The first
> page contains a 24-bit RGB preview image, followed by grayscale spectral band images (16-bit grayscale). The files utilize tag system of TIFF files to store the spectral band center wavelengths in tag 65000 as list of 32-bit floating point values, and tag 65111 to store a free-form ASCII metadata string. The metadata string contains information about the imaging setup, image processing and miscellaneous measurement data (blood pressure and oxygen saturation before and after measurement).
> 
> Annotation files are likewise multipage TIFF images. Each page of the annotation image file contains a binary black-and-white mask image and has the annotation class stored as an ASCII-string in tag 65001.
> 
> Python functions for reading and writing spectral image TIFFs and annotation mask TIFFs are provided in the spectral_tiffs.py file in the database root directory.
> 
> Complete spectral image database is 34 GB in size.

**Comment by vtecftwy** [comment]
There is some code [here](https://cs.uef.fi/pub/color/spectra/ODSI-DB/software/spectral_tiffs.py) that allows to read a TIFF file page per page. It uses tifffile package [here](https://pypi.org/project/tifffile/) and [github](https://github.com/cgohlke/tifffile/) but if we can avoid the dependency, it may be better

**Comment by vtecftwy** [comment]
Just did a few experiments in a notebook and we can do what we want just with PIL.

For the image themselves, it is super simple to extract the RGB using PIL.Image. 
`im = PIL.Image.open(path2TIFF)` will load the image with only the three RGB channels. 
Then we can than save the image again as jpg for instance to create the new dataset.

To extract each of the pages, we can do it with ImageSequence:
`im = Image.open(path2masks)`
`for i, page in enumerate(ImageSequence.Iterator(im)):`
`    display(page)`
will display each of the masks

The only thing that need to be done from here is to extract the name of the class for each of the masks. Will look at this later.
