### ISSUE TITLE
🧈Improve / Remove integration to nbdev

### ISSUE THREAD

**Issue by jfthuong** [unpackAI/unpackai#7]
We are currently using `nbdev` for deploying the code.

We should explore to see if we should
* Remove it
* Improve the integration to ease the collaboration of code

More details on `nbdev` here: https://nbdev.fast.ai/#

**Comment by raynardj** [comment]
### When we run nbdev:
> It's 2 command lines ran under git root folder, that will
* We go through some basic test mentioned in the notebook
* We generate **py script**
* We create **documentation**

### The steps about removing
As generated things are just there, removing nbdev should have been a process to remove this mechanism, not the py or documentation already there.

So by removing nbdev, we **don't have to do anything**, as long as anything in ```./unpackai``` folder and ```./docs``` shouldn't be generated from notebooks...anymore... 

As ```./nbs```, the folder contained many notebooks are just notebooks in the github to be experimented with. Note books are not compiled into pypi wheel even.

That being said, still the auto generated documentation is kinda lame, so we should remove the documentation, the traditional way

**Comment by jfthuong** [comment]
We leave it for the moment. To be revised after collaborative development for few months
