### ISSUE TITLE
🎃 pyscript compatibility

### ISSUE THREAD

**Issue by raynardj** [unpackAI/unpackai#78]
# 🎃 pyscript compatibility
**Describe the bug**

As @jfthuong pointed out in lark

>  It would be nice to move the magics outside "utils" because it prevents from being able to import it from pure python script (like for example in a streamlit app)

**To Reproduce**
Running at non-ipython notebook
```python
from unpackai.utils import *
```

**Screenshots**
![image](https://user-images.githubusercontent.com/27149981/142545666-7236f228-49f4-41d0-a73e-44efbf1f23fc.png)

**Comment by jfthuong** [comment]
I tried (unsucessfully) this code in utils:

```
# Code to allow being able to import from outside Jupyter
try:
    hasattr(magic, "register_cell_magic")
except NameError:

    class MockupIPython:
        def __init__(self):
            """Dummy class"""

        def register_cell_magic(self, func, *args, **kwargs):
            return func

    magic = MockupIPython()
```

Maybe it could be not far away from that

**Comment by raynardj** [comment]
> I tried (unsucessfully) this code in utils:
> 
> ```python
> # Code to allow being able to import from outside Jupyter
> try:
>     hasattr(magic, "register_cell_magic")
> except NameError:
> 
>     class MockupIPython:
>         def __init__(self):
>             """Dummy class"""
> 
>         def register_cell_magic(self, func, *args, **kwargs):
>             return func
> 
>     magic = MockupIPython()
> ```
> 
> Maybe it could be not far away from that

Yes, not far away, I experimented with this functionality on and off, this one works

https://github.com/unpackAI/unpackai/blob/5c6ff1ff141b15430ccf02cab34e9690ec168fda/unpackai/utils.py#L34-L47

**Comment by raynardj** [comment]
![image](https://user-images.githubusercontent.com/27149981/142558480-8297db4e-ac93-45d9-a8e6-b7c352738a21.png)

Clearly it's not working yet

**Comment by raynardj** [comment]
> ![image](https://user-images.githubusercontent.com/27149981/142558480-8297db4e-ac93-45d9-a8e6-b7c352738a21.png)
> 
> Clearly it's not working yet

hmmmm... maybe I can add colab compatibility by specify this special case

**Comment by raynardj** [comment]
![image](https://user-images.githubusercontent.com/27149981/142573531-9272edc2-df9d-4ea3-bdc7-43e3ef00672d.png)
This time it works, and no error when run pyscript
