### ISSUE TITLE
🏗 Restructure Things

### ISSUE THREAD

**Issue by raynardj** [unpackAI/unpackai#8]
# 🏗 Restructure Things
> More refined way to arrange things

## Current
> The order represent the loading priority, the later ones can import things from earlier ones
unpackai
* utils (things I can not categorize for now)
* turk (interactive labeling tools)
    * image (interactive labeling tools for images)
* cosine (visualize embedding, interactive similarity search on embedding entities)
* nlp (tools for nlp)

**Comment by raynardj** [comment]
## import everything by task
eg. 
```python
from unpackai.visual.all import *
```

**Comment by jfthuong** [comment]
We could also do
```python

from unpackai import vision
...
vision.InterpEmbeddingVision(...)
```

**Comment by raynardj** [comment]
## 🎲 Decided structure
> Per our discussion on sep 20th. 10am@ zoom
* We use @jfthuong 's propose, as the major backbone structure
```python
from unpackai import tabular
tabular.no_missing_values(...)
```
* And also create an ```all.py``` script for DL101 accessibility, as it's existence should not impact on the usage of above structure
```python
from unpackai.tabular.all import *
no_missing_values(...)
```
